# Generated by Django 3.1.2 on 2020-10-10 22:26

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=website.models.Candidate.user_path)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
