# Generated by Django 3.1.2 on 2020-10-24 11:24

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=2, null=True, verbose_name='성별')),
                ('kind', models.CharField(blank=True, max_length=20, null=True, verbose_name='종')),
                ('age', models.CharField(blank=True, max_length=20, verbose_name='나이')),
                ('neutering', models.BooleanField(blank=True, null=True)),
                ('adopted', models.CharField(blank=True, choices=[('1', '보호중'), ('2', '가정임보중'), ('3', '입양예약'), ('4', '입양완료')], max_length=2, null=True, verbose_name='보호상태')),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.image_path, verbose_name='대표사진')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('adopt_date', models.DateTimeField(blank=True, null=True, verbose_name='입양날짜')),
            ],
            options={
                'verbose_name_plural': '토끼 목록',
            },
        ),
        migrations.CreateModel(
            name='Protector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('type', models.CharField(blank=True, choices=[('1', '임시보호자'), ('2', '입양자'), ('3', '임보&입양자'), ('4', '기타')], max_length=2, null=True, verbose_name='보호타입')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=2, null=True, verbose_name='성별')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='기타 메모')),
                ('naver_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='네이버 ID')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='닉네임')),
                ('insta_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='인스타 ID')),
            ],
            options={
                'verbose_name_plural': '보호자',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('hide_yn', models.BooleanField(verbose_name='숨김여부')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='수정날짜')),
                ('cand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.candidate', verbose_name='토끼')),
            ],
            options={
                'verbose_name_plural': '입양 홍보글',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.image_path)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.post')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='protector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.protector', verbose_name='보호자'),
        ),
    ]
