# Generated by Django 3.1.2 on 2020-10-12 00:56

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', '남아'), ('F', '여아')], max_length=2)),
                ('birth_year', models.IntegerField()),
                ('adopted', models.BooleanField()),
                ('image', models.ImageField(upload_to=website.models.image_path)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '토끼 목록',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('hide_yn', models.BooleanField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField()),
                ('cand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.image_path)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.post')),
            ],
        ),
    ]
