# Generated by Django 3.1.2 on 2020-11-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='기타 메모'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여'), ('Q', '미상')], max_length=2, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='neutering',
            field=models.BooleanField(blank=True, null=True, verbose_name='중성화 여부'),
        ),
        migrations.AlterField(
            model_name='protector',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여'), ('Q', '미상')], max_length=2, null=True, verbose_name='성별'),
        ),
    ]
