# Generated by Django 3.1.2 on 2020-10-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('naver_id', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=2)),
                ('age', models.IntegerField()),
                ('memo', models.TextField()),
            ],
            options={
                'verbose_name_plural': '임시보호자',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '입양 홍보글'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', '남'), ('F', '여')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='protector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.protector'),
        ),
    ]
